config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }


  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  concern :votesable do
    member do
      patch 'vote_plus'
      patch 'vote_minus'
      patch 'vote_cancel'
    end
  end

    #
    # end
    resources :comments, only: [:destroy]
  scope '(:locale)', :locale => /ru|en/ do
    resources :questions, concerns: [:votesable] do
      resources :answers, concerns: [:votesable], shallow: true do
        patch 'assign_best', on: :member
        resources :comments, only: [:create], defaults: {context: 'answer'}
      end
      resources :comments, only: [:create], defaults: {context: 'question'}
      resources :subscriptions, shallow: true, only: [:create, :destroy]
    end
    resources :searches, only: [:index]

    as :user do
      get 'signup_email', to: 'users/registrations#edit_email', as: :edit_signup_email
      post 'signup_email', to: 'users/registrations#update_email', as: :update_signup_email
    end

    root 'questions#index'
  end

  # root 'questions#index'
  resources :attachments, only: :destroy

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable
  include Formatted

  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  validates :title, :body, presence: true

  scope :daily_questions, lambda {
    where(created_at:
               Date.current.yesterday.beginning_of_day..
                 Date.current.yesterday.end_of_day)
  }

  after_create :subscribe_owner

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  private

  def subscribe_owner
    subscriptions.create!(user_id: user_id)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: :show
  authorize_resource class: Question

  def index
    @questions = Question.all
    respond_with @questions
  end

  def show
    respond_with @question, serializer: SingleQuestionSerializer
  end

  def create
    respond_with(@question = Question.create(strong_params.merge(user: current_resource_owner)))
  end

  protected

  def load_questions
    @questions = Question.all
  end

  def load_question
    @question = Question.find(params['id'])
  end

  def strong_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  include Serialized
  include Broadcasted

  before_action :authenticate_user!, except: [:show, :index]
  before_action :load_question, only: [:show, :update, :destroy]
  before_action :load_questions, only: [:index, :create]

  respond_to :json, only: :create
  respond_to :js, only: [:update]
  respond_to :html, only: [:destroy, :update]

  authorize_resource

  def index
    @question = Question.new
    @question.attachments.build
  end

  def show
    @question_comment = @question.answers.build
    @answer = @question.answers.build
    @answer.attachments.build
  end

  def new; end

  def edit; end

  def create
    @question = current_user.questions.create(strong_params)
    render_json @question
  end

  def update
    respond_with(@question.update(strong_params))
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def broadcasted
    publish_broadcast @question
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def load_questions
    @questions = Question.all
  end

  def strong_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file])
  end
end

app/views/questions/_form.html.slim
#question_form.card-panel
  = form_for @question || :question, data: {remote: "#{ local_assigns.fetch(:remoted, nil) }",
          type: "#{ local_assigns.fetch(:type, nil) }" }  do |f|
    .row
      .input-field.col.s12
        =f.text_field :title
        =f.label :title, class: 'validate', required: true
    .row
      .input-field.col.s12
        = f.text_area :body, class: 'materialize-textarea validate', required: true,
                placeholder: 'Compose new question...'
        = f.label :body
    .row
      .input-field.col.s12
        = render 'application/attachments_nested_forms', f: f
    .row
      .col.s12
        .form-footer
          = button_tag class: 'waves-effect waves-light btn' do
            i.material-icons.right send
            | submit

app/views/questions/_question.html.slim
.collection-item id=dom_id(question)
  .row
    .col.m2.s4
      = question.created_date
    .col.m10.s8
      = link_to question.title, question_path(question)

app/views/questions/_question_l_line.html.slim
h2.question-title
  =@question.title
.question-body
  = @question.body

app/views/questions/index.html.slim
- provide(:title, t('page.home'))

#QuestionsList
  .questions-list
  - if @questions.any?
    br
    h1 List of questions
    .collection
      = render @questions
  - else
    .collection
      h1.center No questions


- if can? :create, Question
  .question-form-wrapper.hidden id=('question-form-wrapper')
    h3.center Ask Question
    = render 'form', remoted: true, type: :json
    .center
  = render 'shared/add_btn', id: 'add_question_btn', target: '#question-form-wrapper'

app/views/questions/index.ru.html.slim
- provide(:title, t('page.home'))

#QuestionsList
  .questions-list
  - if @questions.any?
    br
    h1 Вопросы
    .collection
      = render @questions
  - else
    .collection
      h1.center No questions


- if can? :create, Question
  .question-form-wrapper.hidden id=('question-form-wrapper')
    h3.center Задайте вопрос
    = render 'form', remoted: true, type: :json
    .center
  = render 'shared/add_btn', id: 'add_question_btn', target: '#question-form-wrapper'

app/views/questions/show.html.slim
- provide(:title, 'Question page')
.card id='QuestionPage'
  .question-block.collection-item data-question="#{@question.id}" id= "question-#{@question.id}"
    span.chip.subscribe-block.right
      - if current_user && current_user.subscribed_to?(@question)
        span.unsubscribe
          = link_to 'unsubscribe', subscription_path(@question.subscriptions.ids), method: :delete, remote: true
      - else
        - if can? :create, Subscription
          span.subscribe
            = link_to 'subscribe', question_subscriptions_path(@question), method: :post, remote: true
    .row
      .col.s10
        .question-rendered.card-content
          = render 'questions/question_l_line'
        ul
          = render 'attachments/attachments', target: @question
      .col.s2.center
        .card-content
          = render 'shared/vote_container', object: @question, part: 'question'
    ul.list-inline.question-control-block.card-action
      - if can? :modify, @question
        li
          = link_to @question, class: 'btn-floating red', method: :delete, id: "delete-question-#{@question.id}"
            i.material-icons delete
        li
          button.script-item-toggle.btn-floating.green data-target='#question_form-edit-wrapper' id= ("edit-question-#{@question.id}")
            i.material-icons mode_edit
      - if can? :create, Comment
        li
          button.script-item-toggle.btn-floating.teal data-target="#question-comment-wrapper-#{@question.id}" id= ("comment-question-#{@question.id}")
            i.material-icons comment
.question-edit-wrapper.hidden id=('question_form-edit-wrapper')
  = render 'questions/form', remoted: true

.collection.comment-wrapper.hidden id=("question-comment-wrapper-#{@question.id}")
  .collection-item
    = render 'comments/form',
            comment: @question.comments.new,
            object: @question,
            name: 'Question',
            target: "#QuestionCommentsList-#{@question.id}"

.collection id = ("QuestionCommentsList-#{@question.id}")
  - if @question.comments.present?
    = render @question.comments

- if !@question.answers.present?
  p No answers
#answersList.collection
  - if @question.answers.present?
    = render @question.answers
- if can? :create, Answer
  .answer-wrapper
    h4 Write answer
    = render 'answers/form', answer: @question.answers.new

app/views/questions/update.js.erb
var form = $('#question_form' + '<%= @question.id %>');
var target = $('#question-' + <%= @question.id %> + ' ' + '.question-rendered');
var message, color;

<% if @question.errors.present? %>
  color = 'red';

  <% @question.errors.each do |field, msg| %>
  message = "<%= j msg %>";
  alertFunc(message, color);
<% end %>

<% else %>

  $(target).html("<%= j render 'question_l_line' %></div>");

  <% if flash[:notice].present? %>
    message = "<%=j flash[:notice] %>";
    color = 'green';
    alertFunc(message, color);
  <% end %>


//hide form
  $('#question_form-edit-wrapper').toggleClass('hidden');

//remove alert
  $("form .alert").remove();
  $('#question_form-edit-wrapper').toggle();

//  ItemToggle($('.script-item-toggle'));

<% end %>