config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }


  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  concern :votesable do
    member do
      patch 'vote_plus'
      patch 'vote_minus'
      patch 'vote_cancel'
    end
  end

    #
    # end
    resources :comments, only: [:destroy]
  scope '(:locale)', :locale => /ru|en/ do
    resources :questions, concerns: [:votesable] do
      resources :answers, concerns: [:votesable], shallow: true do
        patch 'assign_best', on: :member
        resources :comments, only: [:create], defaults: {context: 'answer'}
      end
      resources :comments, only: [:create], defaults: {context: 'question'}
      resources :subscriptions, shallow: true, only: [:create, :destroy]
    end
    resources :searches, only: [:index]

    as :user do
      get 'signup_email', to: 'users/registrations#edit_email', as: :edit_signup_email
      post 'signup_email', to: 'users/registrations#update_email', as: :update_signup_email
    end

    root 'questions#index'
  end

  # root 'questions#index'
  resources :attachments, only: :destroy

  mount ActionCable.server => '/cable'
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true, optional: true

  mount_uploader :file, FileUploader
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!

  authorize_resource

  def destroy
    @attachment = Attachment.find(params['id'])
    @attachment.destroy if current_user.owner_of?(@attachment.attachable)
  end
end

app/views/attachments/_attachments.html.slim
- if target.attachments.present?
  li.attachments-block.card-content
    - target.attachments.each do |a|
      ul id="attachment-id-#{a.id}"
        li
          = link_to a.file.identifier, a.file.url, target: '_blank'
        - if current_user && current_user.owner_of?(a.attachable)
          li
            = link_to '[x]', attachment_path(a), method: :delete, remote: true,
                  class: 'delete_attachment btn red'

app/views/attachments/destroy.js.erb
li = $("#attachment-id-<%= @attachment.id %>");
ul = li.closest('ul');
container = li.closest('.attachments-block');

li.remove();

if (ul.has("li").length === 0) {
  container.remove();
}