config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }


  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  concern :votesable do
    member do
      patch 'vote_plus'
      patch 'vote_minus'
      patch 'vote_cancel'
    end
  end

    #
    # end
    resources :comments, only: [:destroy]
  scope '(:locale)', :locale => /ru|en/ do
    resources :questions, concerns: [:votesable] do
      resources :answers, concerns: [:votesable], shallow: true do
        patch 'assign_best', on: :member
        resources :comments, only: [:create], defaults: {context: 'answer'}
      end
      resources :comments, only: [:create], defaults: {context: 'question'}
      resources :subscriptions, shallow: true, only: [:create, :destroy]
    end
    resources :searches, only: [:index]

    as :user do
      get 'signup_email', to: 'users/registrations#edit_email', as: :edit_signup_email
      post 'signup_email', to: 'users/registrations#update_email', as: :update_signup_email
    end

    root 'questions#index'
  end

  # root 'questions#index'
  resources :attachments, only: :destroy

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable
  include Formatted

  belongs_to :question
  belongs_to :user
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :votes, as: :votesable, dependent: :destroy

  validates :body, length: { minimum: 6 }, presence: true
  validates :question_id, presence: true
  validates :best, uniqueness: { scope: :question_id }, if: :best?

  default_scope { order('best DESC, created_at DESC') }

  after_create :notify_mailer

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  def set_best
    transaction do
      question.answers.where(best: true).each do |answer|
        answer.update!(best: false)
      end
      update!(best: true)
    end
  end

  def files
    files = []
    attachments.each { |a| files << { id: a.id, file_url: a.file.url, file_name: a.file.identifier } }
  end

  private

  def notify_mailer
    NewAnswerNotificationJob.perform_later self
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  include Serialized
  include Broadcasted

  before_action :verify_requested_format!
  before_action :authenticate_user!
  before_action :load_answer, except: [:create]
  before_action :load_question, only: [:update]

  respond_to :js, :json

  authorize_resource

  def update
    @answer.update(strong_params)
    respond_with(@answer)
  end

  def create
    @question = Question.find(params[:question_id])
    respond_with(@answer = @question.answers.create(strong_params.merge(user: current_user)))
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def assign_best
    respond_with(@answer.set_best)
  end

  private

  def broadcasted
    publish_broadcast @answer
  end

  def strong_params
    params.require(:answer).permit(:body, attachments_attributes: [:file])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def load_question
    @question = Answer.find(params[:id]).question
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource class: Answer

  before_action :load_question, only: [:index, :create]
  before_action :load_answer, only: :show

  def index
    respond_with @question.answers
  end

  def show
    respond_with @answer, serializer: SingleAnswerSerializer
  end

  def create
    respond_with(@answer = @question.answers.create(strong_params.merge(user: current_resource_owner)))
  end

  private

  def load_question
    @question = Question.find(params['question_id'])
  end

  def load_answer
    @answer = Answer.find(params['id'])
  end

  def strong_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  .answer-block.collection-item class=("parent-question-#{answer.question.id}") id= "answer-block-#{answer.id}"
    .answer id = "answer-#{answer.id}"
      .row
        .col.s10
          .renders-text
            ul.answer-rendered
              = render partial: 'answers/answer_l_line', locals: { object: answer }
          ul.answer-rendered-attachment
            = render 'attachments/attachments', target: answer
        .col.s2.center
          .card-content
            = render 'shared/vote_container', object: answer, part: 'answer'
      ul.list-inline.answer-panel.card-action
        - if can? :modify, answer
          li
            = button_to answer, method: :delete, remote: true,
                    class: 'btn-floating red', id: "delete-answer-#{answer.id}" do
              i.material-icons delete
          li
            button.script-item-toggle.btn-floating.green data-target="#answer-form-wrapper-#{answer.id}" id=("edit-answer-#{answer.id}")
              i.material-icons mode_edit
        - if can? :create, Comment
          li
            button.btn-floating.teal.script-item-toggle data-target="#answer-comment-wrapper-#{answer.id}" id= ("comment-answer-#{answer.id}")
              i.material-icons comment
        - if answer.best
          li
            b.text-success The best answer
        - if can? :assign_best, answer
          = link_to 'Assign best', assign_best_answer_path(answer), method: :patch, remote: true, class: 'btn-link'
    .edit-form-wrapper.hidden id=("answer-form-wrapper-#{answer.id}")
      h5 Edit Answer
      = render 'answers/form', answer: answer
    h6 Comments:
    hr
    .comment-wrapper.hidden id=("answer-comment-wrapper-#{answer.id}")
      .collection-item
        = render 'comments/form', comment: answer.comments.new, object: answer, name: 'Answer', target: "#AnswerCommentsList-#{answer.id}"
    .comment-list id = "AnswerCommentsList-#{answer.id}"
      - if answer.comments.present?
        = render answer.comments

app/views/answers/_answer_l_line.html.slim
li = object.created_date
li.answer-body = object.body

app/views/answers/_form.html.slim
.card
  = form_for shallow_resource(@question, answer), data: {type: "#{ local_assigns.fetch(:type, nil) }"  }, remote: true do |f|
    .card-content
      .row
        .input-field.col.s12
          = f.text_area :body, class: 'materialize-textarea validate',
                  required: true, rows: 5, placeholder: 'Compose new answer...'
          =f.label :body, class: 'validate'
      .attachment-nested
        = f.fields_for :attachments do |a|
          = render 'application/attachment_fields', f: a
        .input-field.col.s12
          = link_to_add_association f, :attachments,
                  class: 'btn-floating green attach-file-answer'
            i.material-icons attach_file
    .card-action
      ul.list-inline
        li
          = button_tag class: 'waves-effect waves-light btn' do
            i.material-icons.right send
            | submit

app/views/answers/assign_best.js.erb
$('#answersList').html('<%= j render @answer.question.answers %>');
var message,
    color;

<% if flash[:success] %>
  message = "<%=j flash[:success] %>";
  color = 'green';
  alertFunc(message, color);

<% elsif flash[:error]  %>
  color = 'red';
  message = "<%=j flash[:success] %>";
  Materialize.toast(message, 4000, 'red');
<% end %>

app/views/answers/create.js.erb
var form = $('#new_answer'),
    alert = form.find('#error_validation'),
    message,
    color;

container = $('.attachment-nested .nested-fields');
<% if @answer.errors.any? %>
  color = 'red';

  <% @answer.errors.each do |field, msg| %>
    message = "<%= j  msg %>";
    alertFunc(message, color);
  <% end %>

  <% if flash[:alert].present? %>
    message = "<%=j flash[:alert] %>";
    alertFunc(message, color);
  <% end %>

<% else %>

  $('#answersList').append('<%= j render @answer %>');
  form.find('#answer_body').val('');
  container.toggle();

  <% if flash[:notice].present? %>
    message = "<%=j flash[:notice] %>";
    color = 'green';
    alertFunc(message, color);
  <% end %>

<% end %>

app/views/answers/destroy.js.erb
$("#answer-block-<%= @answer.id %>").detach();

<% if flash[:alert].present? %>
  color = 'red';
  message = "<%=j flash[:notice] %>";
  alertFunc(message, color);
<% end %>

<% if flash[:notice].present? %>
  message = "<%=j flash[:notice] %>";
  color = 'green';
  alertFunc(message, color);
<% end %>

app/views/answers/edit.html.slim
- provide(:title, 'Edit Answer')
.container
  = render 'answers/form_edit'

app/views/answers/index.html.slim
.container
  h1 Answer#index
  p Find me in app/views/answer/index.html.slim

app/views/answers/new.html.slim
.container
  h1 Answer#show
  p Find me in app/views/answer/show.html.slim

app/views/answers/update.js.erb
var form = $('#answer-form-wrapper-' + '<%= @answer.id %>'),
    message,
    color;

<% if @answer.errors.present? %>
  color = 'red';

  <% @answer.errors.each do |field, msg| %>
    message = "<%= j msg %>";
    alertFunc(message, color);
  <% end %>
  <% if flash[:alert].present? %>
    message = "<%=j flash[:notice] %>";
    alertFunc(message, color);
  <% end %>
<% else %>

  $('#answer-' + <%= @answer.id %> + ' .renders-text').replaceWith(
      "<ul class='answer-rendered'><%= j render partial: 'answers/answer_l_line', locals: {object: @answer}%></ul>");

  <% if flash[:notice].present? %>
    message = "<%=j flash[:notice] %>";
    color = 'green';
    alertFunc(message, color);
  <% end %>

  $(form).toggle();
<% end %>